
--AGRUPAR POR SOLICITAÇÂO e AGRUPAR POR MES E ANOS DE EMISSÂO -> GROUP BY
-- MOSTRAR SOMA POR MES -> sum(), MONTH(), WHERE, 
-- RETIRAR OS RESGISTROS DELETADOS D_E_L_E_T_
-- CONSIDERAR SOLICITAÇÃO ENCERRADAS -> Olhar os filtros da tela da solicitação de compras no Protheus


SELECT 'SHOPCIDADAO'AS EMPRESA, C1_FILIAL, DATAEMISSAO, COUNT(*) AS QUANTIDADEDESOLICITACAO
FROM (
		SELECT C1_FILIAL, C1_NUM, SUBSTRING (C1_EMISSAO,1,8) AS DATAEMISSAO
		FROM SC1020
		WHERE C1_EMISSAO BETWEEN '20200101' AND '20211031'
		AND D_E_L_E_T_ <> '*'
		AND C1_PEDIDO <> ' '
		GROUP BY C1_FILIAL, C1_NUM,SUBSTRING (C1_EMISSAO,1,8)
	)   AS TAB
GROUP BY C1_FILIAL, DATAEMISSAO

UNION ALL

SELECT 'MINASCIDADAO'AS EMPRESA, C1_FILIAL, DATAEMISSAO, COUNT(*) AS QUANTIDADEDESOLICITACAO
FROM (
		SELECT C1_FILIAL, C1_NUM, SUBSTRING (C1_EMISSAO,1,8) AS DATAEMISSAO
		FROM SC1070
		WHERE C1_EMISSAO BETWEEN '20200101' AND '20211031'
		AND D_E_L_E_T_ <> '*'
		AND C1_PEDIDO <> ' '
		GROUP BY C1_FILIAL, C1_NUM,SUBSTRING (C1_EMISSAO,1,8)
	)   AS TAB
GROUP BY C1_FILIAL, DATAEMISSAO

UNION ALL

SELECT 'CENTRALCIDADANIA'AS EMPRESA, C1_FILIAL, DATAEMISSAO, COUNT(*) AS QUANTIDADEDESOLICITACAO
FROM (
		SELECT C1_FILIAL, C1_NUM, SUBSTRING (C1_EMISSAO,1,8) AS DATAEMISSAO
		FROM SC1090
		WHERE C1_EMISSAO BETWEEN '20200101' AND '20211031'
		AND D_E_L_E_T_ <> '*'
		AND C1_PEDIDO <> ' '
		GROUP BY C1_FILIAL, C1_NUM,SUBSTRING (C1_EMISSAO,1,8)
	)   AS TAB
GROUP BY C1_FILIAL, DATAEMISSAO

UNION ALL

SELECT 'SPCIDADAO'AS EMPRESA, C1_FILIAL, DATAEMISSAO, COUNT(*) AS QUANTIDADEDESOLICITACAO
FROM (
		SELECT C1_FILIAL, C1_NUM, SUBSTRING (C1_EMISSAO,1,8) AS DATAEMISSAO
		FROM SC1170
		WHERE C1_EMISSAO BETWEEN '20200101' AND '20211031'
		AND D_E_L_E_T_ <> '*'
		AND C1_PEDIDO <> ' '
		GROUP BY C1_FILIAL, C1_NUM,SUBSTRING (C1_EMISSAO,1,8)
	)   AS TAB
GROUP BY C1_FILIAL, DATAEMISSAO