SELECT 'SPCIDADAO'AS EMPRESA, C1_FILIAL, DATAEMISSAO, COUNT(*) AS QUANTIDADEDESOLICITACAO, DATAPRENOTA, DATEDIFF (DAY, DATAEMISSAO,DATAPRENOTA) AS DIFERENCADIA
FROM (
		SELECT C1_FILIAL, C1_NUM, SUBSTRING (C1_EMISSAO,1,8) AS DATAEMISSAO, SUBSTRING (D1_DTDIGIT,1,8) AS DATAPRENOTA
		FROM SC1170 AS SC1
		INNER JOIN SC7170 AS SC7
		ON C1_FILIAL = C7_FILIAL
		AND C1_NUM = C7_NUMSC
		AND C1_ITEM = C7_ITEMSC
		AND C1_PRODUTO = C7_PRODUTO
		INNER JOIN SD1170 AS SD1
		ON C7_FILIAL = D1_FILIAL
		AND C7_PRODUTO = D1_COD
		AND C7_NUM = D1_PEDIDO
		AND C7_ITEM = D1_ITEMPC
		AND C7_FORNECE = D1_FORNECE
		WHERE C1_EMISSAO BETWEEN '20200101' AND '20211031'
		AND SD1.D_E_L_E_T_ <> '*'
		AND SC7.D_E_L_E_T_ <> '*'
		AND SC1.D_E_L_E_T_ <> '*'
		AND C1_PEDIDO <> ' '
		GROUP BY C1_FILIAL, C1_NUM,SUBSTRING (C1_EMISSAO,1,8), SUBSTRING (D1_DTDIGIT,1,8)
	)   AS TAB
GROUP BY C1_FILIAL, DATAEMISSAO, DATAPRENOTA
